
/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

/*features int[0,1] __SELECTED_FEATURE_overloaded;
features int[0,1] __SELECTED_FEATURE_weight;
features int[0,1] __SELECTED_FEATURE_empty;


features int[0,1] __SELECTED_FEATURE_twothirdsfull;
features int[0,1] __SELECTED_FEATURE_executivefloor;

features int[0,1] __SELECTED_FEATURE_Verify;
features int[0,1] __SELECTED_FEATURE_AutoResponder;
features int[0,1] __SELECTED_FEATURE_Forward;  */

#pragma merger(0,"featureselect.i","")
int __SELECTED_FEATURE_base  ;
//int __SELECTED_FEATURE_weight  ;
//int __SELECTED_FEATURE_empty  ;
int __SELECTED_FEATURE_twothirdsfull  ;
int __SELECTED_FEATURE_executivefloor  ;
//int __SELECTED_FEATURE_overloaded  ;
int __GUIDSL_ROOT_PRODUCTION  ;
int select_one(void) ;
void select_features(void) ;
void select_helpers(void) ;
int valid_product(void) ;


int select_one(void) 
{ int retValue_acc ;
  int choice = [0,1]; //__VERIFIER_nondet_int();

  retValue_acc = choice;
  return (retValue_acc);

}

void select_features(void) 
{ 

  __SELECTED_FEATURE_base = 1;
//  __SELECTED_FEATURE_weight = select_one();
//  __SELECTED_FEATURE_empty = select_one();
  __SELECTED_FEATURE_twothirdsfull = select_one();
  __SELECTED_FEATURE_executivefloor = select_one();
//  __SELECTED_FEATURE_overloaded = select_one();
  return;

}

void select_helpers(void) 
{ 

  __GUIDSL_ROOT_PRODUCTION = 1;
  return;
}

int valid_product(void) 
{ int retValue_acc ;
  int tmp ;

//  if ((__SELECTED_FEATURE_overloaded==0) || (__SELECTED_FEATURE_weight==1)) {
//      if ((__SELECTED_FEATURE_twothirdsfull==0) || (__SELECTED_FEATURE_weight==1)) {
 
          if (__SELECTED_FEATURE_base==1) {
            tmp = 1;
          } else {
            tmp = 0;
          }
/*        } else {
          tmp = 0;
        }
    } else {
      tmp = 0;
    }
*/ 
  retValue_acc = tmp;
  return (retValue_acc);
 
}

#pragma merger(0,"Person.i","")
int getWeight(int person ) ;
int getOrigin(int person ) ;
int getDestination(int person ) ;

int getWeight(int person ) 
{ int retValue_acc ;

  if (person == 0) {
    retValue_acc = 40;
    //return (retValue_acc);
  } else {
    if (person == 1) {
      retValue_acc = 40;
      //return (retValue_acc);
    } else {
      if (person == 2) {
        retValue_acc = 40;
        //return (retValue_acc);
      } else {
        if (person == 3) {
          retValue_acc = 40;
          //return (retValue_acc);
        } else {
          if (person == 4) {
            retValue_acc = 30;
            //return (retValue_acc);
          } else {
            if (person == 5) {
              retValue_acc = 150;
              //return (retValue_acc);
            } else {
              retValue_acc = 0;
              //return (retValue_acc);
            }
          }
        }
      }
    }
  }
  return (retValue_acc);
}
int getOrigin(int person ) 
{ int retValue_acc ;

  
  if (person == 0) {
    retValue_acc = 4;
    //return (retValue_acc);
  } else {
    if (person == 1) {
      retValue_acc = 3;
      //return (retValue_acc);
    } else {
      if (person == 2) {
        retValue_acc = 2;
        //return (retValue_acc);
      } else {
        if (person == 3) {
          retValue_acc = 1;
          //return (retValue_acc);
        } else {
          if (person == 4) {
            retValue_acc = 0;
            //return (retValue_acc);
          } else {
            if (person == 5) {
              retValue_acc = 1;
              //return (retValue_acc);
            } else {
              retValue_acc = 0;
              //return (retValue_acc);
            }
          }
        }
      }
    }
  }
  return (retValue_acc);
}

int getDestination(int person ) 
{ int retValue_acc ;

  if (person == 0) {
    retValue_acc = 0;
    //return (retValue_acc);
  } else {
    if (person == 1) {
      retValue_acc = 0;
      //return (retValue_acc);
    } else {
      if (person == 2) {
        retValue_acc = 1;
        //return (retValue_acc);
      } else {
        if (person == 3) {
          retValue_acc = 3;
          //return (retValue_acc);
        } else {
          if (person == 4) {
            retValue_acc = 1;
            //return (retValue_acc);
          } else {
            if (person == 5) {
              retValue_acc = 3;
              //return (retValue_acc);
            } else {
              retValue_acc = 0;
              //return (retValue_acc);
            }
          }
        }
      }
    }
  }
  return (retValue_acc);
}


#pragma merger(0,"Floor.i","")
int isFloorCalling(int floorID ) ;
void resetCallOnFloor(int floorID ) ;
void callOnFloor(int floorID ) ;
int isPersonOnFloor(int person , int floor ) ;
void initPersonOnFloor(int person , int floor ) ;
void removePersonFromFloor(int person , int floor ) ;
int isTopFloor(int floorID ) ;
void initFloors(void) ;
int calls_0  ;
int calls_1  ;
int calls_2  ;
int calls_3  ;
int calls_4  ;
int personOnFloor_0_0  ;
int personOnFloor_0_1  ;
int personOnFloor_0_2  ;
int personOnFloor_0_3  ;
int personOnFloor_0_4  ;
int personOnFloor_1_0  ;
int personOnFloor_1_1  ;
int personOnFloor_1_2  ;
int personOnFloor_1_3  ;
int personOnFloor_1_4  ;
int personOnFloor_2_0  ;
int personOnFloor_2_1  ;
int personOnFloor_2_2  ;
int personOnFloor_2_3  ;
int personOnFloor_2_4  ;
int personOnFloor_3_0  ;
int personOnFloor_3_1  ;
int personOnFloor_3_2  ;
int personOnFloor_3_3  ;
int personOnFloor_3_4  ;
int personOnFloor_4_0  ;
int personOnFloor_4_1  ;
int personOnFloor_4_2  ;
int personOnFloor_4_3  ;
int personOnFloor_4_4  ;
int personOnFloor_5_0  ;
int personOnFloor_5_1  ;
int personOnFloor_5_2  ;
int personOnFloor_5_3  ;
int personOnFloor_5_4  ;
void initFloors(void) 
{ 

  {
  calls_0 = 0;
  calls_1 = 0;
  calls_2 = 0;
  calls_3 = 0;
  calls_4 = 0;
  personOnFloor_0_0 = 0;
  personOnFloor_0_1 = 0;
  personOnFloor_0_2 = 0;
  personOnFloor_0_3 = 0;
  personOnFloor_0_4 = 0;
  personOnFloor_1_0 = 0;
  personOnFloor_1_1 = 0;
  personOnFloor_1_2 = 0;
  personOnFloor_1_3 = 0;
  personOnFloor_1_4 = 0;
  personOnFloor_2_0 = 0;
  personOnFloor_2_1 = 0;
  personOnFloor_2_2 = 0;
  personOnFloor_2_3 = 0;
  personOnFloor_2_4 = 0;
  personOnFloor_3_0 = 0;
  personOnFloor_3_1 = 0;
  personOnFloor_3_2 = 0;
  personOnFloor_3_3 = 0;
  personOnFloor_3_4 = 0;
  personOnFloor_4_0 = 0;
  personOnFloor_4_1 = 0;
  personOnFloor_4_2 = 0;
  personOnFloor_4_3 = 0;
  personOnFloor_4_4 = 0;
  personOnFloor_5_0 = 0;
  personOnFloor_5_1 = 0;
  personOnFloor_5_2 = 0;
  personOnFloor_5_3 = 0;
  personOnFloor_5_4 = 0;
  return;
}
}
int isFloorCalling(int floorID ) 
{ int retValue_acc ;

  if (floorID == 0) {
    retValue_acc = calls_0;
  } else {
    if (floorID == 1) {
      retValue_acc = calls_1;
    } else {
      if (floorID == 2) {
        retValue_acc = calls_2;
      } else {
        if (floorID == 3) {
          retValue_acc = calls_3;
        } else {
          if (floorID == 4) {
            retValue_acc = calls_4;
          } else {
			retValue_acc = 0;
          }
        }
      }
    }
  }
  
  return (retValue_acc);
}

void resetCallOnFloor(int floorID ) 
{ 

  if (floorID == 0) {
    calls_0 = 0;
  } else {
    if (floorID == 1) {
      calls_1 = 0;
    } else {
      if (floorID == 2) {
        calls_2 = 0;
      } else {
        if (floorID == 3) {
          calls_3 = 0;
        } else {
          if (floorID == 4) {
            calls_4 = 0;
          } else {

          }
        }
      }
    }
  }
  return;
}

void callOnFloor(int floorID ) 
{ 

  {
  if (floorID == 0) {
    calls_0 = 1;
  } else {
    if (floorID == 1) {
      calls_1 = 1;
    } else {
      if (floorID == 2) {
        calls_2 = 1;
      } else {
        if (floorID == 3) {
          calls_3 = 1;
        } else {
          if (floorID == 4) {
            calls_4 = 1;
          } else {

          }
        }
      }
    }
  }
  return;
}
}

int isPersonOnFloor(int person , int floor ) 
{ int retValue_acc ;

  {
  if (floor == 0) {
    if (person == 0) {
      retValue_acc = personOnFloor_0_0;
      //return (retValue_acc);
    } else {
      if (person == 1) {
        retValue_acc = personOnFloor_1_0;
        //return (retValue_acc);
      } else {
        if (person == 2) {
          retValue_acc = personOnFloor_2_0;
          //return (retValue_acc);
        } else {
          if (person == 3) {
            retValue_acc = personOnFloor_3_0;
            //return (retValue_acc);
          } else {
            if (person == 4) {
              retValue_acc = personOnFloor_4_0;
              //return (retValue_acc);
            } else {
              if (person == 5) {
                retValue_acc = personOnFloor_5_0;
                //return (retValue_acc);
              } else {
				retValue_acc = 0;
              }
            }
          }
        }
      }
    }
  } else {
    if (floor == 1) {
      if (person == 0) {
        retValue_acc = personOnFloor_0_1;
        //return (retValue_acc);
      } else {
        if (person == 1) {
          retValue_acc = personOnFloor_1_1;
          //return (retValue_acc);
        } else {
          if (person == 2) {
            retValue_acc = personOnFloor_2_1;
            //return (retValue_acc);
          } else {
            if (person == 3) {
              retValue_acc = personOnFloor_3_1;
              //return (retValue_acc);
            } else {
              if (person == 4) {
                retValue_acc = personOnFloor_4_1;
                //return (retValue_acc);
              } else {
                if (person == 5) {
                  retValue_acc = personOnFloor_5_1;
                  //return (retValue_acc);
                } else {
					retValue_acc = 0;
                }
              }
            }
          }
        }
      }
    } else {
      if (floor == 2) {
        if (person == 0) {
          retValue_acc = personOnFloor_0_2;
          //return (retValue_acc);
        } else {
          if (person == 1) {
            retValue_acc = personOnFloor_1_2;
            //return (retValue_acc);
          } else {
            if (person == 2) {
              retValue_acc = personOnFloor_2_2;
              //return (retValue_acc);
            } else {
              if (person == 3) {
                retValue_acc = personOnFloor_3_2;
                //return (retValue_acc);
              } else {
                if (person == 4) {
                  retValue_acc = personOnFloor_4_2;
                  //return (retValue_acc);
                } else {
                  if (person == 5) {
                    retValue_acc = personOnFloor_5_2;
                    //return (retValue_acc);
                  } else {
					retValue_acc = 0;
                  }
                }
              }
            }
          }
        }
      } else {
        if (floor == 3) {
          if (person == 0) {
            retValue_acc = personOnFloor_0_3;
            //return (retValue_acc);
          } else {
            if (person == 1) {
              retValue_acc = personOnFloor_1_3;
              //return (retValue_acc);
            } else {
              if (person == 2) {
                retValue_acc = personOnFloor_2_3;
                //return (retValue_acc);
              } else {
                if (person == 3) {
                  retValue_acc = personOnFloor_3_3;
                  //return (retValue_acc);
                } else {
                  if (person == 4) {
                    retValue_acc = personOnFloor_4_3;
                    //return (retValue_acc);
                  } else {
                    if (person == 5) {
                      retValue_acc = personOnFloor_5_3;
                      //return (retValue_acc);
                    } else {
						retValue_acc = 0;
                    }
                  }
                }
              }
            }
          }
        } else {
          if (floor == 4) {
            if (person == 0) {
              retValue_acc = personOnFloor_0_4;
              //return (retValue_acc);
            } else {
              if (person == 1) {
                retValue_acc = personOnFloor_1_4;
                //return (retValue_acc);
              } else {
                if (person == 2) {
                  retValue_acc = personOnFloor_2_4;
                  //return (retValue_acc);
                } else {
                  if (person == 3) {
                    retValue_acc = personOnFloor_3_4;
                    //return (retValue_acc);
                  } else {
                    if (person == 4) {
                      retValue_acc = personOnFloor_4_4;
                      //return (retValue_acc);
                    } else {
                      if (person == 5) {
                        retValue_acc = personOnFloor_5_4;
                        //return (retValue_acc);
                      } else {
						retValue_acc = 0;
                      }
                    }
                  }
                }
              }
            }
          } else {
				retValue_acc = 0;
          }
        }
      }
    }
  }
  
  return (retValue_acc);
}
}

void initPersonOnFloor(int person , int floor ) 
{ 

  {
  if (floor == 0) {
    if (person == 0) {
      personOnFloor_0_0 = 1;
    } else {
      if (person == 1) {
        personOnFloor_1_0 = 1;
      } else {
        if (person == 2) {
          personOnFloor_2_0 = 1;
        } else {
          if (person == 3) {
            personOnFloor_3_0 = 1;
          } else {
            if (person == 4) {
              personOnFloor_4_0 = 1;
            } else {
              if (person == 5) {
                personOnFloor_5_0 = 1;
              } else {

              }
            }
          }
        }
      }
    }
  } else {
    if (floor == 1) {
      if (person == 0) {
        personOnFloor_0_1 = 1;
      } else {
        if (person == 1) {
          personOnFloor_1_1 = 1;
        } else {
          if (person == 2) {
            personOnFloor_2_1 = 1;
          } else {
            if (person == 3) {
              personOnFloor_3_1 = 1;
            } else {
              if (person == 4) {
                personOnFloor_4_1 = 1;
              } else {
                if (person == 5) {
                  personOnFloor_5_1 = 1;
                } else {

                }
              }
            }
          }
        }
      }
    } else {
      if (floor == 2) {
        if (person == 0) {
          personOnFloor_0_2 = 1;
        } else {
          if (person == 1) {
            personOnFloor_1_2 = 1;
          } else {
            if (person == 2) {
              personOnFloor_2_2 = 1;
            } else {
              if (person == 3) {
                personOnFloor_3_2 = 1;
              } else {
                if (person == 4) {
                  personOnFloor_4_2 = 1;
                } else {
                  if (person == 5) {
                    personOnFloor_5_2 = 1;
                  } else {

                  }
                }
              }
            }
          }
        }
      } else {
        if (floor == 3) {
          if (person == 0) {
            personOnFloor_0_3 = 1;
          } else {
            if (person == 1) {
              personOnFloor_1_3 = 1;
            } else {
              if (person == 2) {
                personOnFloor_2_3 = 1;
              } else {
                if (person == 3) {
                  personOnFloor_3_3 = 1;
                } else {
                  if (person == 4) {
                    personOnFloor_4_3 = 1;
                  } else {
                    if (person == 5) {
                      personOnFloor_5_3 = 1;
                    } else {

                    }
                  }
                }
              }
            }
          }
        } else {
          if (floor == 4) {
            if (person == 0) {
              personOnFloor_0_4 = 1;
            } else {
              if (person == 1) {
                personOnFloor_1_4 = 1;
              } else {
                if (person == 2) {
                  personOnFloor_2_4 = 1;
                } else {
                  if (person == 3) {
                    personOnFloor_3_4 = 1;
                  } else {
                    if (person == 4) {
                      personOnFloor_4_4 = 1;
                    } else {
                      if (person == 5) {
                        personOnFloor_5_4 = 1;
                      } else {

                      }
                    }
                  }
                }
              }
            }
          } else {

          }
        }
      }
    }
  }
  {
  callOnFloor(floor);
  }
  return;
}
}

void removePersonFromFloor(int person , int floor ) 
{ 

  {
  if (floor == 0) {
    if (person == 0) {
      personOnFloor_0_0 = 0;
    } else {
      if (person == 1) {
        personOnFloor_1_0 = 0;
      } else {
        if (person == 2) {
          personOnFloor_2_0 = 0;
        } else {
          if (person == 3) {
            personOnFloor_3_0 = 0;
          } else {
            if (person == 4) {
              personOnFloor_4_0 = 0;
            } else {
              if (person == 5) {
                personOnFloor_5_0 = 0;
              } else {

              }
            }
          }
        }
      }
    }
  } else {
    if (floor == 1) {
      if (person == 0) {
        personOnFloor_0_1 = 0;
      } else {
        if (person == 1) {
          personOnFloor_1_1 = 0;
        } else {
          if (person == 2) {
            personOnFloor_2_1 = 0;
          } else {
            if (person == 3) {
              personOnFloor_3_1 = 0;
            } else {
              if (person == 4) {
                personOnFloor_4_1 = 0;
              } else {
                if (person == 5) {
                  personOnFloor_5_1 = 0;
                } else {

                }
              }
            }
          }
        }
      }
    } else {
      if (floor == 2) {
        if (person == 0) {
          personOnFloor_0_2 = 0;
        } else {
          if (person == 1) {
            personOnFloor_1_2 = 0;
          } else {
            if (person == 2) {
              personOnFloor_2_2 = 0;
            } else {
              if (person == 3) {
                personOnFloor_3_2 = 0;
              } else {
                if (person == 4) {
                  personOnFloor_4_2 = 0;
                } else {
                  if (person == 5) {
                    personOnFloor_5_2 = 0;
                  } else {

                  }
                }
              }
            }
          }
        }
      } else {
        if (floor == 3) {
          if (person == 0) {
            personOnFloor_0_3 = 0;
          } else {
            if (person == 1) {
              personOnFloor_1_3 = 0;
            } else {
              if (person == 2) {
                personOnFloor_2_3 = 0;
              } else {
                if (person == 3) {
                  personOnFloor_3_3 = 0;
                } else {
                  if (person == 4) {
                    personOnFloor_4_3 = 0;
                  } else {
                    if (person == 5) {
                      personOnFloor_5_3 = 0;
                    } else {

                    }
                  }
                }
              }
            }
          }
        } else {
          if (floor == 4) {
            if (person == 0) {
              personOnFloor_0_4 = 0;
            } else {
              if (person == 1) {
                personOnFloor_1_4 = 0;
              } else {
                if (person == 2) {
                  personOnFloor_2_4 = 0;
                } else {
                  if (person == 3) {
                    personOnFloor_3_4 = 0;
                  } else {
                    if (person == 4) {
                      personOnFloor_4_4 = 0;
                    } else {
                      if (person == 5) {
                        personOnFloor_5_4 = 0;
                      } else {

                      }
                    }
                  }
                }
              }
            }
          } else {

          }
        }
      }
    }
  }
  {
  resetCallOnFloor(floor);
  }
  return;
}
}

int isTopFloor(int floorID ) 
{ int retValue_acc ;

  
  retValue_acc = floorID == 4;
  return (retValue_acc);

}

#pragma merger(0,"UnitTests.i","")
void timeShift(void) ;
int isBlocked(void) ;
void printState(void) ;
void initTopDown(void) ;
void initBottomUp(void) ;
int weight  =    0;
int maximumWeight  =    100;
int executiveFloor  =    4;
int blocked  =    0;
int cleanupTimeShifts  =    12;

void spec1(void) 
{ int tmp ;
  int tmp___0 ;
  int i ;
  int tmp___1 ;

  
  initBottomUp();
  tmp = getOrigin(5);
  initPersonOnFloor(5, tmp);
  printState();
  tmp___0 = getOrigin(2);
  initPersonOnFloor(2, tmp___0);
  printState();
  i = 0;
  

  tmp___1 = isBlocked();
  while ((i < cleanupTimeShifts) && (tmp___1 != 1)) {
    
    timeShift();
    printState();
    i = i + 1;
    
	tmp___1 = isBlocked();
  }

  return;
}

void spec14(void) 
{ int tmp ;
  int tmp___0 ;
  int i ;
  int tmp___1 ;

  
  
  initTopDown();
  tmp = getOrigin(5);
  initPersonOnFloor(5, tmp);
  printState();
  timeShift();
  timeShift();
  timeShift();
  timeShift();
  tmp___0 = getOrigin(0);
  initPersonOnFloor(0, tmp___0);
  printState();
  i = 0;
  
  tmp___1 = isBlocked();
  while ((i < cleanupTimeShifts) && (tmp___1 != 1)) {

    timeShift();
    printState();
    i = i + 1;
    tmp___1 = isBlocked();
  }
  
  return;
}

#pragma merger(0,"Specification2_spec.i","")
int areDoorsOpen(void) ;
int getCurrentFloorID(void) ;
int floorButtons_spc2_0  ;
int floorButtons_spc2_1  ;
int floorButtons_spc2_2  ;
int floorButtons_spc2_3  ;
int floorButtons_spc2_4  ;
void __utac_acc__Specification2_spec__1(void) 
{ 

  
  floorButtons_spc2_0 = 0;
  floorButtons_spc2_1 = 0;
  floorButtons_spc2_2 = 0;
  floorButtons_spc2_3 = 0;
  floorButtons_spc2_4 = 0;
  return;

}

void __utac_acc__Specification2_spec__2(int floor ) 
{ 

  if (floor == 0) {
    floorButtons_spc2_0 = 1;
  } else {
    if (floor == 1) {
      floorButtons_spc2_1 = 1;
    } else {
      if (floor == 2) {
        floorButtons_spc2_2 = 1;
      } else {
        if (floor == 3) {
          floorButtons_spc2_3 = 1;
        } else {
          if (floor == 4) {
            floorButtons_spc2_4 = 1;
          } else {

          }
        }
      }
    }
  }
  return;

}

void __utac_acc__Specification2_spec__3(void) 
{ int floor ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;

  tmp = getCurrentFloorID();
  floor = tmp;
  
	tmp___4 = areDoorsOpen();
    if ((floor == 0) && (floorButtons_spc2_0==1) && (tmp___4==1)) {
        floorButtons_spc2_0 = 0;
  } else {
	tmp___3 = areDoorsOpen();
    if ((floor == 1) && (floorButtons_spc2_1==1) && (tmp___3==1)) {
          floorButtons_spc2_1 = 0;
    } else {
	tmp___2 = areDoorsOpen();
    if ((floor == 2) && (floorButtons_spc2_2==1) && (tmp___2==1)) {
            floorButtons_spc2_2 = 0;
      } else {
	  tmp___1 = areDoorsOpen();
      if ((floor == 3) && (floorButtons_spc2_3==1) && (tmp___1==1)) {
              floorButtons_spc2_3 = 0;
        } else {
      tmp___0 = areDoorsOpen();
      if ((floor == 4) && (floorButtons_spc2_4==1) && (tmp___0==1)) {
                floorButtons_spc2_4 = 0;
          } else {

          }
        }
      }
    }
  }
  return;

}

void __utac_acc__Specification2_spec__4(void) 
{ 

  {
  if (floorButtons_spc2_0) {
    {
    assert(0);
    }
  } else {
    if (floorButtons_spc2_1) {
      {
      assert(0);
      }
    } else {
      if (floorButtons_spc2_2) {
        {
        assert(0);
        }
      } else {
        if (floorButtons_spc2_3) {
          {
          assert(0);
          }
        } else {
          if (floorButtons_spc2_4) {
            {
            assert(0);
            }
          } else {

          }
        }
      }
    }
  }
  return;
}
}
#pragma merger(0,"scenario.i","")
void bigMacCall(void) ;
void cleanup(void) ;
void test(void) 
{ 

  bigMacCall();
  cleanup();
  
  return;
}
#pragma merger(0,"Test.i","")
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status ) ;
int get_nondetMinMax07(void) 
{ int retValue_acc ;
  int nd ;
  nd = [0,7]; //__VERIFIER_nondet_int();

  
  if (nd == 0) {
    retValue_acc = 0;
    //return (retValue_acc);
  } else {
    if (nd == 1) {
      retValue_acc = 1;
      //return (retValue_acc);
    } else {
      if (nd == 2) {
        retValue_acc = 2;
        //return (retValue_acc);
      } else {
        if (nd == 3) {
          retValue_acc = 3;
          //return (retValue_acc);
        } else {
          if (nd == 4) {
            retValue_acc = 4;
            //return (retValue_acc);
          } else {
            if (nd == 5) {
              retValue_acc = 5;
              //return (retValue_acc);
            } else {
              if (nd == 6) {
                retValue_acc = 6;
                //return (retValue_acc);
              } else {
                if (nd == 7) {
                  retValue_acc = 7;
                  //return (retValue_acc);
                } else {

                }
              }
            }
          }
        }
      }
    }
  }
  return (retValue_acc);
}

void bobCall(void) 
{ int tmp ;

  {
  tmp = getOrigin(0);
  initPersonOnFloor(0, tmp);
  }
  return;

}

void aliceCall(void) 
{ int tmp ;


  tmp = getOrigin(1);
  initPersonOnFloor(1, tmp);
  
  return;

}

void angelinaCall(void) 
{ int tmp ;


  tmp = getOrigin(2);
  initPersonOnFloor(2, tmp);
  
  return;

}

void chuckCall(void) 
{ int tmp ;

  {
  {
  tmp = getOrigin(3);
  initPersonOnFloor(3, tmp);
  }
  return;
}
}
void monicaCall(void) 
{ int tmp ;

  {
  {
  tmp = getOrigin(4);
  initPersonOnFloor(4, tmp);
  }
  return;
}
}
void bigMacCall(void) 
{ int tmp ;

  {
  {
  tmp = getOrigin(5);
  initPersonOnFloor(5, tmp);
  }
  return;
}
}
void threeTS(void) 
{ 

  {
  {
  timeShift();
  timeShift();
  timeShift();
  }
  return;
}
}
int isIdle(void) ;
void cleanup(void) 
{ int i ;
  int tmp ;
  int tmp___0 ;
  int __cil_tmp4 ;

  
  timeShift();
  i = 0;
  
 
  __cil_tmp4 = cleanupTimeShifts - 1;
  tmp___0 = isBlocked();
  while ((i < __cil_tmp4) && (tmp___0 != 1)) {
    while_8_continue: /* CIL Label */ ;
    
    
    tmp = isIdle();
    
    if (tmp==0) {
      
      timeShift();
     
    }
    i = i + 1;
	tmp___0 = isBlocked();
  }
  
  return;

}

void randomSequenceOfActions(void) 
{ int maxLength ;
  int tmp ;
  int counter ;
  int action ;
  int tmp___0 ;
  int origin ;
  int tmp___1 ;
  int tmp___2 ;

  
  
  maxLength = 4;
  tmp = [0,1]; //__VERIFIER_nondet_int();
  
  if (tmp) {
    {
    initTopDown();
    }
  } else {
    {
    initBottomUp();
    }
  }
  counter = 0;
  
  while (counter < maxLength) {

    
    counter = counter + 1;
    tmp___0 = get_nondetMinMax07();
    action = tmp___0;
    
    if (action < 6) {
      {
      tmp___1 = getOrigin(action);
      origin = tmp___1;
      initPersonOnFloor(action, origin);
      }
    } else {
      if (action == 6) {
        {
        timeShift();
        }
      } else {
        if (action == 7) {
          {
          timeShift();
          timeShift();
          timeShift();
          }
        } else {

        }
      }
    }
    
    tmp___2 = isBlocked();
    
    if (tmp___2) {
      break; 
    } else {

    }
  }
  
  
  cleanup();
  
  return;
}

void runTest_Simple(void) 
{ 

  bigMacCall();
  angelinaCall();
  cleanup();
  
  return;

}

void Specification1(void) 
{ 

  bigMacCall();
  angelinaCall();
  cleanup();
  
  return;

}
void Specification2(void) 
{ 

  bigMacCall();
  cleanup();
  
  return;

}
void Specification3(void) 
{ 

  bobCall();
  timeShift();
  timeShift();
  timeShift();
  timeShift();
  timeShift();
  bobCall();
  cleanup();
  
  return;

}

void setup(void) 
{ 

  runTest_Simple();
  return;

}

void runTest(void) 
{ 


  __utac_acc__Specification2_spec__1();
  test();
  __utac_acc__Specification2_spec__4();
  
  return;

}

void select_helpers(void) ;
void select_features(void) ;
int valid_product(void) ;
int main(void) 
{ int retValue_acc ;
  int tmp ;
  
  select_helpers();
  select_features();
  tmp = valid_product();
  
  if (tmp==1) {
    
    setup();
    runTest();
    
  } else {

  }
  retValue_acc = 0;
  return (retValue_acc);
  //return (retValue_acc);

}



#pragma merger(0,"Elevator.i","")
void enterElevator(int p ) ;
int isEmpty(void) ;
int isAnyLiftButtonPressed(void) ;
int buttonForFloorIsPressed(int floorID ) ;
int isExecutiveFloorCalling(void) ;
int isExecutiveFloor(int floorID ) ;
int currentHeading  =    1;
int currentFloorID  =    0;
int persons_0  ;
int persons_1  ;
int persons_2  ;
int persons_3  ;
int persons_4  ;
int persons_5  ;
int doorState  =    1;
int floorButtons_0  ;
int floorButtons_1  ;
int floorButtons_2  ;
int floorButtons_3  ;
int floorButtons_4  ;
void initTopDown(void) 
{ 

  {
  {
  currentFloorID = 4;
  currentHeading = 0;
  floorButtons_0 = 0;
  floorButtons_1 = 0;
  floorButtons_2 = 0;
  floorButtons_3 = 0;
  floorButtons_4 = 0;
  persons_0 = 0;
  persons_1 = 0;
  persons_2 = 0;
  persons_3 = 0;
  persons_4 = 0;
  persons_5 = 0;
  initFloors();
  }
  return;
}
}
void initBottomUp(void) 
{ 

  {
  {
  currentFloorID = 0;
  currentHeading = 1;
  floorButtons_0 = 0;
  floorButtons_1 = 0;
  floorButtons_2 = 0;
  floorButtons_3 = 0;
  floorButtons_4 = 0;
  persons_0 = 0;
  persons_1 = 0;
  persons_2 = 0;
  persons_3 = 0;
  persons_4 = 0;
  persons_5 = 0;
  initFloors();
  }
  return;
}
}

int isBlocked__before__overloaded(void) 
{ int retValue_acc ;

  {
  retValue_acc = 0;
  return (retValue_acc);
  return (retValue_acc);
}
}
int isBlocked__role__overloaded(void) 
{ int retValue_acc ;

  
  retValue_acc = blocked;
  return (retValue_acc);
  //return (retValue_acc);

}

int isBlocked(void) 
{ int retValue_acc ;

  
  #if (__SELECTED_FEATURE_overloaded) 
    
    retValue_acc = isBlocked__role__overloaded();
    
    //return (retValue_acc);
  #else 
    
    retValue_acc = isBlocked__before__overloaded();
    
    //return (retValue_acc);
  #endif
  return (retValue_acc);
}

void enterElevator__before__weight(int p ) 
{ 

  if (p == 0) {
    persons_0 = 1;
  } else {
    if (p == 1) {
      persons_1 = 1;
    } else {
      if (p == 2) {
        persons_2 = 1;
      } else {
        if (p == 3) {
          persons_3 = 1;
        } else {
          if (p == 4) {
            persons_4 = 1;
          } else {
            if (p == 5) {
              persons_5 = 1;
            } else {

            }
          }
        }
      }
    }
  }
  return;

}

void enterElevator__role__weight(int p ) 
{ int tmp ;

  enterElevator__before__weight(p);
  tmp = getWeight(p);
  weight = weight + tmp;
  
  return;

}

void enterElevator(int p ) 
{ 

  #if (__SELECTED_FEATURE_weight) 
    
    enterElevator__role__weight(p);

  #else 
    
    enterElevator__before__weight(p);

  #endif
  return; 
	
}
void leaveElevator__before__weight(int p ) 
{ 

  if (p == 0) {
    persons_0 = 0;
  } else {
    if (p == 1) {
      persons_1 = 0;
    } else {
      if (p == 2) {
        persons_2 = 0;
      } else {
        if (p == 3) {
          persons_3 = 0;
        } else {
          if (p == 4) {
            persons_4 = 0;
          } else {
            if (p == 5) {
              persons_5 = 0;
            } else {

            }
          }
        }
      }
    }
  }
  return;

}

void leaveElevator__role__weight(int p ) 
{ int tmp ;

  leaveElevator__before__weight(p);
  tmp = getWeight(p);
  weight = weight - tmp;
  
  return;

}

void leaveElevator__before__empty(int p ) 
{ 
  #if (__SELECTED_FEATURE_weight) 
    leaveElevator__role__weight(p);    
  #else
    leaveElevator__before__weight(p);
  #endif
  return;
}

void leaveElevator__role__empty(int p ) 
{ int tmp ;


  leaveElevator__before__empty(p);
  tmp = isEmpty();
  
  if (tmp) {
    floorButtons_0 = 0;
    floorButtons_1 = 0;
    floorButtons_2 = 0;
    floorButtons_3 = 0;
    floorButtons_4 = 0;
  } else {

  }
  return;

}

void leaveElevator(int p ) 
{ 

  #if (__SELECTED_FEATURE_empty) 
    leaveElevator__role__empty(p);
    
  #else 
    leaveElevator__before__empty(p);
  #endif
	
  return;
	
}

void pressInLiftFloorButton(int floorID ) 
{ int __utac__ad__arg1 ;


  __utac__ad__arg1 = floorID;
  __utac_acc__Specification2_spec__2(__utac__ad__arg1);
  
  if (floorID == 0) {
    floorButtons_0 = 1;
  } else {
    if (floorID == 1) {
      floorButtons_1 = 1;
    } else {
      if (floorID == 2) {
        floorButtons_2 = 1;
      } else {
        if (floorID == 3) {
          floorButtons_3 = 1;
        } else {
          if (floorID == 4) {
            floorButtons_4 = 1;
          } else {

          }
        }
      }
    }
  }
  return;

}

void resetFloorButton(int floorID ) 
{ 

  if (floorID == 0) {
    floorButtons_0 = 0;
  } else {
    if (floorID == 1) {
      floorButtons_1 = 0;
    } else {
      if (floorID == 2) {
        floorButtons_2 = 0;
      } else {
        if (floorID == 3) {
          floorButtons_3 = 0;
        } else {
          if (floorID == 4) {
            floorButtons_4 = 0;
          } else {

          }
        }
      }
    }
  }
  return;

}

int getCurrentFloorID(void) 
{ int retValue_acc ;

  retValue_acc = currentFloorID;
  return (retValue_acc);
  //return (retValue_acc);
}

int areDoorsOpen(void) 
{ int retValue_acc ;

  retValue_acc = doorState;
  return (retValue_acc);
  //return (retValue_acc);
}

int buttonForFloorIsPressed(int floorID ) 
{ int retValue_acc ;

  
  if (floorID == 0) {
    retValue_acc = floorButtons_0;
    //return (retValue_acc);
  } else {
    if (floorID == 1) {
      retValue_acc = floorButtons_1;
      //return (retValue_acc);
    } else {
      if (floorID == 2) {
        retValue_acc = floorButtons_2;
        //return (retValue_acc);
      } else {
        if (floorID == 3) {
          retValue_acc = floorButtons_3;
          //return (retValue_acc);
        } else {
          if (floorID == 4) {
            retValue_acc = floorButtons_4;
            //return (retValue_acc);
          } else {
            retValue_acc = 0;
            //return (retValue_acc);
          }
        }
      }
    }
  }
  return (retValue_acc);

}
int getCurrentHeading(void) 
{ int retValue_acc ;


  retValue_acc = currentHeading;
  return (retValue_acc);
  //return (retValue_acc);

}

int isEmpty(void) 
{ int retValue_acc ;

  if (persons_0 == 1) {
    retValue_acc = 0;
    //return (retValue_acc);
  } else {
    if (persons_1 == 1) {
      retValue_acc = 0;
      //return (retValue_acc);
    } else {
      if (persons_2 == 1) {
        retValue_acc = 0;
        //return (retValue_acc);
      } else {
        if (persons_3 == 1) {
          retValue_acc = 0;
          //return (retValue_acc);
        } else {
          if (persons_4 == 1) {
            retValue_acc = 0;
            //return (retValue_acc);
          } else {
            if (persons_5 == 1) {
              retValue_acc = 0;
              //return (retValue_acc);
            } else {
				retValue_acc = 1;
            }
          }
        }
      }
    }
  }
  
  return (retValue_acc);
}

int anyStopRequested(void) 
{ int retValue_acc ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;

  tmp___3 = isFloorCalling(0);

  if (tmp___3==1) {
    retValue_acc = 1;
    //return (retValue_acc);
  } else {
    if (floorButtons_0==1) {
      retValue_acc = 1;
      //return (retValue_acc);
    } else {
      {
      tmp___2 = isFloorCalling(1);
      }
      if (tmp___2==1) {
        retValue_acc = 1;
        //return (retValue_acc);
      } else {
        if (floorButtons_1==1) {
          retValue_acc = 1;
          //return (retValue_acc);
        } else {
          {
          tmp___1 = isFloorCalling(2);
          }
          if (tmp___1==1) {
            retValue_acc = 1;
            //return (retValue_acc);
          } else {
            if (floorButtons_2==1) {
              retValue_acc = 1;
              //return (retValue_acc);
            } else {
              {
              tmp___0 = isFloorCalling(3);
              }
              if (tmp___0==1) {
                retValue_acc = 1;
                //return (retValue_acc);
              } else {
                if (floorButtons_3==1) {
                  retValue_acc = 1;
                  //return (retValue_acc);
                } else {
                  {
                  tmp = isFloorCalling(4);
                  }
                  if (tmp==1) {
                    retValue_acc = 1;
                    //return (retValue_acc);
                  } else {
                    if (floorButtons_4==1) {
                      retValue_acc = 1;
                      //return (retValue_acc);
                    } else {
						retValue_acc = 0;
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  
  return (retValue_acc);
}


int isIdle(void) 
{ int retValue_acc ;
  int tmp ;

  tmp = anyStopRequested();
  retValue_acc = tmp == 0;
  
  //return (retValue_acc);
  return (retValue_acc);

}

int stopRequestedInDirection__before__twothirdsfull(int dir , int respectFloorCalls ,
                                                    int respectInLiftCalls ) 
{ int retValue_acc ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;
  int tmp___9 ;

  {
  if (dir == 1) {
    {
    tmp = isTopFloor(currentFloorID);
    }
    if (tmp==1) {
      retValue_acc = 0;
      //return (retValue_acc);
    } else {
    tmp___4 = isFloorCalling(0);
    if ((currentFloorID < 0) && (respectFloorCalls==1) && (tmp___4==1)) {

          retValue_acc = 1;
          //return (retValue_acc);
    } else {
      if ((currentFloorID < 0) && (respectInLiftCalls==1) && (floorButtons_0==1)) {

            retValue_acc = 1;

      } else {
        tmp___3 = isFloorCalling(1);
        if ((currentFloorID < 1) && (respectFloorCalls==1) && (tmp___3==1)) {

              retValue_acc = 1;
              //return (retValue_acc);

        } else {

          if ((currentFloorID < 1) && (respectInLiftCalls==1) && (floorButtons_1==1)) {

                retValue_acc = 1;
                //return (retValue_acc);

          } else {
			tmp___2 = isFloorCalling(2);
            if ((currentFloorID < 2) && (respectFloorCalls==1) && (tmp___2==1)) {

                  retValue_acc = 1;
                  //return (retValue_acc);
            } else {
              if ((currentFloorID < 2) && (respectInLiftCalls==1) && (floorButtons_2==1)) {
 
                    retValue_acc = 1;
                    //return (retValue_acc);

              } else {
				tmp___1 = isFloorCalling(3); 
                if ((currentFloorID < 3) && (respectFloorCalls==1) && (tmp___1==1)) {

                      retValue_acc = 1;
                      //return (retValue_acc);

                } else {
                  if ((currentFloorID < 3) && (respectInLiftCalls==1) && (floorButtons_3==1)) {

                        retValue_acc = 1;
                        //return (retValue_acc);

                  } else {
					tmp___0 = isFloorCalling(4); 
                    if ((currentFloorID < 4) && (respectFloorCalls==1) && (tmp___0==1)) {

                          retValue_acc = 1;
                          //return (retValue_acc);

                    } else {
                      if ((currentFloorID < 4) && (respectInLiftCalls==1) && (floorButtons_4==1)) {

                            retValue_acc = 1;
                            //return (retValue_acc);
                      } else {
                        retValue_acc = 0;
                        return (retValue_acc);
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  } else {
    if (currentFloorID == 0) {
      retValue_acc = 0;
      //return (retValue_acc);
    } else {

    }
	tmp___9 = isFloorCalling(0);
    if ((currentFloorID > 0) && (respectFloorCalls==1) && (tmp___9==1)) {
          retValue_acc = 1;
          //return (retValue_acc);

    } else {

      if ((currentFloorID > 0) && (respectInLiftCalls==1) && (floorButtons_0==1)) {

            retValue_acc = 1;
            //return (retValue_acc);

      } else {
		tmp___8 = isFloorCalling(1); 
        if ((currentFloorID > 1) && (respectFloorCalls==1) && (tmp___8==1)) {

              retValue_acc = 1;
              //return (retValue_acc);

        } else {

          if ((currentFloorID > 1) && (respectInLiftCalls==1) && (floorButtons_1==1)) {

                retValue_acc = 1;
                //return (retValue_acc);

          } else {
			tmp___7 = isFloorCalling(2);
            if ((currentFloorID > 2) && (respectFloorCalls==1) && (tmp___7==1)) {

                  retValue_acc = 1;
                  //return (retValue_acc);

            } else {
              if ((currentFloorID > 2) && (respectInLiftCalls==1) && (floorButtons_2==1)) {

                    retValue_acc = 1;
                    //return (retValue_acc);

              } else {
				tmp___6 = isFloorCalling(3); 
                if ((currentFloorID > 3) && (respectFloorCalls==1) && (tmp___6==1)) {

                      retValue_acc = 1;
                      //return (retValue_acc);

                } else {

                  if ((currentFloorID > 3) && (respectInLiftCalls==1) && (floorButtons_3==1)) {

                        retValue_acc = 1;
                        //return (retValue_acc);

                  } else {
					tmp___5 = isFloorCalling(4);
                    if ((currentFloorID > 4) && (respectFloorCalls==1) && (tmp___5==1)) {

                          retValue_acc = 1;
                          //return (retValue_acc);

                    } else {
                      if ((currentFloorID > 4) && (respectInLiftCalls==1) && (floorButtons_4==1)) {

                            retValue_acc = 1;
                            //return (retValue_acc);

                      } else {
                        retValue_acc = 0;
                        //return (retValue_acc);
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
	  
	  
  return (retValue_acc);
}
}



int stopRequestedInDirection__role__twothirdsfull(int dir , int respectFloorCalls ,
                                                  int respectInLiftCalls ) 
{ int retValue_acc ;
  int overload ;
  int buttonPressed ;
  int tmp ;
  int __cil_tmp8 ;
  int __cil_tmp9 ;

  __cil_tmp8 = maximumWeight * 2;
  __cil_tmp9 = __cil_tmp8 / 3;
  overload = weight > __cil_tmp9;
  tmp = isAnyLiftButtonPressed();
  buttonPressed = tmp;
  
  if (overload) {
    if (buttonPressed) {
      {
      retValue_acc = stopRequestedInDirection__before__twothirdsfull(dir, 0, respectInLiftCalls);
      }
      //return (retValue_acc);
    } else {
      {
      retValue_acc = stopRequestedInDirection__before__twothirdsfull(dir, respectFloorCalls,
                                                                     respectInLiftCalls);
      }
      //return (retValue_acc);
    }
  } else {
    {
    retValue_acc = stopRequestedInDirection__before__twothirdsfull(dir, respectFloorCalls,
                                                                   respectInLiftCalls);
    }
    //return (retValue_acc);
  }
  return (retValue_acc);

}

int stopRequestedInDirection__before__executivefloor(int dir , int respectFloorCalls ,
                                                     int respectInLiftCalls ) 
{ int retValue_acc ;

  
  if (__SELECTED_FEATURE_twothirdsfull==1) {
    {
    retValue_acc = stopRequestedInDirection__role__twothirdsfull(dir, respectFloorCalls,
                                                                 respectInLiftCalls);
    }
    //return (retValue_acc);
  } else {
    {
    retValue_acc = stopRequestedInDirection__before__twothirdsfull(dir, respectFloorCalls,
                                                                   respectInLiftCalls);
    }
    //return (retValue_acc);
  }
  return (retValue_acc);

}

int stopRequestedInDirection__role__executivefloor(int dir , int respectFloorCalls ,
                                                   int respectInLiftCalls ) 
{ int retValue_acc ;
  int tmp ;
  int tmp___0 ;
  int __cil_tmp7 ;
  int __cil_tmp8 ;

  {
  {
  tmp___0 = isExecutiveFloorCalling();
  }
  if (tmp___0) {
    {
    tmp = getCurrentFloorID();
    __cil_tmp7 = dir == 1;
    __cil_tmp8 = tmp < executiveFloor;
    retValue_acc = __cil_tmp8 == __cil_tmp7;
    }
    //return (retValue_acc);
  } else {
    {
    retValue_acc = stopRequestedInDirection__before__executivefloor(dir, respectFloorCalls,
                                                                    respectInLiftCalls);
    }
    //return (retValue_acc);
  }
  return (retValue_acc);
}
}

int stopRequestedInDirection(int dir , int respectFloorCalls , int respectInLiftCalls ) 
{ int retValue_acc ;

  {
  if (__SELECTED_FEATURE_executivefloor==1) {
    {
    retValue_acc = stopRequestedInDirection__role__executivefloor(dir, respectFloorCalls,
                                                                  respectInLiftCalls);
    }
    //return (retValue_acc);
  } else {
    {
    retValue_acc = stopRequestedInDirection__before__executivefloor(dir, respectFloorCalls,
                                                                    respectInLiftCalls);
    }
    //return (retValue_acc);
  }
  return (retValue_acc);
}
}

int isAnyLiftButtonPressed(void) 
{ int retValue_acc ;

  {
  if (floorButtons_0) {
    retValue_acc = 1;
    //return (retValue_acc);
  } else {
    if (floorButtons_1) {
      retValue_acc = 1;
      //return (retValue_acc);
    } else {
      if (floorButtons_2) {
        retValue_acc = 1;
        //return (retValue_acc);
      } else {
        if (floorButtons_3) {
          retValue_acc = 1;
          //return (retValue_acc);
        } else {
          if (floorButtons_4) {
            retValue_acc = 1;
            //return (retValue_acc);
          } else {
            retValue_acc = 0;
            //return (retValue_acc);
          }
        }
      }
    }
  }
  return (retValue_acc);
}
}

void continueInDirection(int dir ) 
{ int tmp ;

  {
  currentHeading = dir;
  if (currentHeading == 1) {
    {
    tmp = isTopFloor(currentFloorID);
    }
    if (tmp==1) {
      currentHeading = 0;
    } else {

    }
  } else {
    if (currentFloorID == 0) {
      currentHeading = 1;
    } else {

    }
  }
  if (currentHeading == 1) {
    currentFloorID = currentFloorID + 1;
  } else {
    currentFloorID = currentFloorID - 1;
  }
  return;
}
}

int stopRequestedAtCurrentFloor__before__twothirdsfull(void) 
{ int retValue_acc ;
  int tmp ;
  int tmp___0 ;

  
  tmp___0 = isFloorCalling(currentFloorID);
  
  if (tmp___0==1) {
    retValue_acc = 1;
    //return (retValue_acc);
  } else {
    
    tmp = buttonForFloorIsPressed(currentFloorID);
    
    if (tmp==1) {
      retValue_acc = 1;
      //return (retValue_acc);
    } else {
      retValue_acc = 0;
      //return (retValue_acc);
    }
  }
  return (retValue_acc);

}

int stopRequestedAtCurrentFloor__role__twothirdsfull(void) 
{ int retValue_acc ;
  int tmp ;
  int tmp___0 ;
  int __cil_tmp4 ;
  int __cil_tmp5 ;

  {
  {
  __cil_tmp4 = maximumWeight * 2;
  __cil_tmp5 = __cil_tmp4 / 3;
  if (weight > __cil_tmp5) {
    {
    tmp = getCurrentFloorID();
    tmp___0 = buttonForFloorIsPressed(tmp);
    retValue_acc = tmp___0 == 1;
    }
    //return (retValue_acc);
  } else {
    {
    retValue_acc = stopRequestedAtCurrentFloor__before__twothirdsfull();
    }
    //return (retValue_acc);
  }
  }
  return (retValue_acc);
}
}

int stopRequestedAtCurrentFloor__before__executivefloor(void) 
{ int retValue_acc ;

  {
  if (__SELECTED_FEATURE_twothirdsfull==1) {
    {
    retValue_acc = stopRequestedAtCurrentFloor__role__twothirdsfull();
    }
    //return (retValue_acc);
  } else {
    {
    retValue_acc = stopRequestedAtCurrentFloor__before__twothirdsfull();
    }
    //return (retValue_acc);
  }
  return (retValue_acc);
}
}

int stopRequestedAtCurrentFloor__role__executivefloor(void) 
{ int retValue_acc ;
  int tmp ;
  int tmp___0 ;


  tmp = isExecutiveFloorCalling();
  
  if (tmp==1) {
    {
    tmp___0 = getCurrentFloorID();
    }
    if (executiveFloor == tmp___0) {
      
      retValue_acc = stopRequestedAtCurrentFloor__before__executivefloor();
      
      //return (retValue_acc);
    } else {
      retValue_acc = 0;
      //return (retValue_acc);
    }
  } else {
    
    retValue_acc = stopRequestedAtCurrentFloor__before__executivefloor();
    
    //return (retValue_acc);
  }
  return (retValue_acc);

}

int stopRequestedAtCurrentFloor(void) 
{ int retValue_acc ;


  if (__SELECTED_FEATURE_executivefloor==1) {
    
    retValue_acc = stopRequestedAtCurrentFloor__role__executivefloor();
    
    //return (retValue_acc);
  } else {
    
    retValue_acc = stopRequestedAtCurrentFloor__before__executivefloor();
    
    //return (retValue_acc);
  }
  return (retValue_acc);

}

int getReverseHeading(int ofHeading ) 
{ int retValue_acc ;

  if (ofHeading == 0) {
    retValue_acc = 1;
    //return (retValue_acc);
  } else {
    retValue_acc = 0;
    //return (retValue_acc);
  }
  return (retValue_acc);
}

void processWaitingOnFloor(int floorID ) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;
  int tmp___9 ;
  int tmp___10 ;

  tmp___0 = isPersonOnFloor(0, floorID);
  
  if (tmp___0==1) {
    
    removePersonFromFloor(0, floorID);
    tmp = getDestination(0);
    pressInLiftFloorButton(tmp);
    enterElevator(0);
    
  } else {

  }
  
  tmp___2 = isPersonOnFloor(1, floorID);
  
  if (tmp___2==1) {
    
    removePersonFromFloor(1, floorID);
    tmp___1 = getDestination(1);
    pressInLiftFloorButton(tmp___1);
    enterElevator(1);
    
  } else {

  }
  
  tmp___4 = isPersonOnFloor(2, floorID);
  
  if (tmp___4==1) {
    
    removePersonFromFloor(2, floorID);
    tmp___3 = getDestination(2);
    pressInLiftFloorButton(tmp___3);
    enterElevator(2);
    
  } else {

  }
  
  tmp___6 = isPersonOnFloor(3, floorID);
  
  if (tmp___6==1) {
    
    removePersonFromFloor(3, floorID);
    tmp___5 = getDestination(3);
    pressInLiftFloorButton(tmp___5);
    enterElevator(3);
    
  } else {

  }
  
  tmp___8 = isPersonOnFloor(4, floorID);
  
  if (tmp___8==1) {
    
    removePersonFromFloor(4, floorID);
    tmp___7 = getDestination(4);
    pressInLiftFloorButton(tmp___7);
    enterElevator(4);
    
  } else {

  }
  
  tmp___10 = isPersonOnFloor(5, floorID);
  
  if (tmp___10==1) {
    
    removePersonFromFloor(5, floorID);
    tmp___9 = getDestination(5);
    pressInLiftFloorButton(tmp___9);
    enterElevator(5);
    
  } else {

  }
  
  resetCallOnFloor(floorID);
  
  return;

}

void timeShift__before__overloaded(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;
  int tmp___9 ;


  tmp___9 = stopRequestedAtCurrentFloor();
  
  if (tmp___9==1) {
    doorState = 1;
    if (persons_0==1) {
      
      tmp = getDestination(0);
      
      if (tmp == currentFloorID) {
        
        leaveElevator(0);
        
      } else {

      }
    } else {

    }
    if (persons_1==1) {
      
      tmp___0 = getDestination(1);
      
      if (tmp___0 == currentFloorID) {
        
        leaveElevator(1);
        
      } else {

      }
    } else {

    }
    if (persons_2==1) {
      
      tmp___1 = getDestination(2);
      
      if (tmp___1 == currentFloorID) {
        
        leaveElevator(2);
        
      } else {

      }
    } else {

    }
    if (persons_3==1) {
      
      tmp___2 = getDestination(3);
      
      if (tmp___2 == currentFloorID) {
        
        leaveElevator(3);
        
      } else {

      }
    } else {

    }
    if (persons_4==1) {
      
      tmp___3 = getDestination(4);
      
      if (tmp___3 == currentFloorID) {
        
        leaveElevator(4);
        
      } else {

      }
    } else {

    }
    if (persons_5==1) {
      
      tmp___4 = getDestination(5);
      
      if (tmp___4 == currentFloorID) {
        
        leaveElevator(5);
        
      } else {

      }
    } else {

    }
    {
    processWaitingOnFloor(currentFloorID);
    resetFloorButton(currentFloorID);
    }
  } else {
    if (doorState == 1) {
      doorState = 0;
    } else {

    }
    {
    tmp___8 = stopRequestedInDirection(currentHeading, 1, 1);
    }
    if (tmp___8==1) {
      
      continueInDirection(currentHeading);
      
    } else {
      {
      tmp___6 = getReverseHeading(currentHeading);
      tmp___7 = stopRequestedInDirection(tmp___6, 1, 1);
      }
      if (tmp___7==1) {
        
        tmp___5 = getReverseHeading(currentHeading);
        continueInDirection(tmp___5);
        
      } else {
        
        continueInDirection(currentHeading);
        
      }
    }
  }
  return;

}

void timeShift__role__overloaded(void) 
{ int tmp ;


  tmp = areDoorsOpen();
  
  if (tmp==1) {
    if (weight > maximumWeight) {
      blocked = 1;
    } else {
      
      blocked = 0;
      timeShift__before__overloaded();
      
    }
  } else {
    
    blocked = 0;
    timeShift__before__overloaded();
    
  }
  return;

}

void timeShift(void) 
{ 

  
  #if (__SELECTED_FEATURE_overloaded)
	{
    timeShift__role__overloaded();
    __utac_acc__Specification2_spec__3();
	}
    //return;
  #else 
    {
    timeShift__before__overloaded();
    __utac_acc__Specification2_spec__3();
    }
	#endif
  
  __utac_acc__Specification2_spec__3();
  
}

/*
void printState__before__overloaded(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  char const   * __restrict  __cil_tmp6 ;
  char const   * __restrict  __cil_tmp7 ;
  char const   * __restrict  __cil_tmp8 ;
  char const   * __restrict  __cil_tmp9 ;
  char const   * __restrict  __cil_tmp10 ;
  char const   * __restrict  __cil_tmp11 ;
  char const   * __restrict  __cil_tmp12 ;
  char const   * __restrict  __cil_tmp13 ;
  char const   * __restrict  __cil_tmp14 ;
  char const   * __restrict  __cil_tmp15 ;
  char const   * __restrict  __cil_tmp16 ;
  char const   * __restrict  __cil_tmp17 ;
  char const   * __restrict  __cil_tmp18 ;
  char const   * __restrict  __cil_tmp19 ;
  char const   * __restrict  __cil_tmp20 ;
  char const   * __restrict  __cil_tmp21 ;
  char const   * __restrict  __cil_tmp22 ;
  char const   * __restrict  __cil_tmp23 ;
  char const   * __restrict  __cil_tmp24 ;
  char const   * __restrict  __cil_tmp25 ;
  char const   * __restrict  __cil_tmp26 ;

  {
  {
  __cil_tmp6 = (char const   * __restrict  )"Elevator ";
  printf(__cil_tmp6);
  }
  if (doorState) {
    {
    __cil_tmp7 = (char const   * __restrict  )"[_]";
    printf(__cil_tmp7);
    }
  } else {
    {
    __cil_tmp8 = (char const   * __restrict  )"[] ";
    printf(__cil_tmp8);
    }
  }
  {
  __cil_tmp9 = (char const   * __restrict  )" at ";
  printf(__cil_tmp9);
  __cil_tmp10 = (char const   * __restrict  )"%i";
  printf(__cil_tmp10, currentFloorID);
  __cil_tmp11 = (char const   * __restrict  )" heading ";
  printf(__cil_tmp11);
  }
  if (currentHeading) {
    {
    __cil_tmp12 = (char const   * __restrict  )"up";
    printf(__cil_tmp12);
    }
  } else {
    {
    __cil_tmp13 = (char const   * __restrict  )"down";
    printf(__cil_tmp13);
    }
  }
  {
  __cil_tmp14 = (char const   * __restrict  )" IL_p:";
  printf(__cil_tmp14);
  }
  if (floorButtons_0) {
    {
    __cil_tmp15 = (char const   * __restrict  )" %i";
    printf(__cil_tmp15, 0);
    }
  } else {

  }
  if (floorButtons_1) {
    {
    __cil_tmp16 = (char const   * __restrict  )" %i";
    printf(__cil_tmp16, 1);
    }
  } else {

  }
  if (floorButtons_2) {
    {
    __cil_tmp17 = (char const   * __restrict  )" %i";
    printf(__cil_tmp17, 2);
    }
  } else {

  }
  if (floorButtons_3) {
    {
    __cil_tmp18 = (char const   * __restrict  )" %i";
    printf(__cil_tmp18, 3);
    }
  } else {

  }
  if (floorButtons_4) {
    {
    __cil_tmp19 = (char const   * __restrict  )" %i";
    printf(__cil_tmp19, 4);
    }
  } else {

  }
  {
  __cil_tmp20 = (char const   * __restrict  )" F_p:";
  printf(__cil_tmp20);
  tmp = isFloorCalling(0);
  }
  if (tmp) {
    {
    __cil_tmp21 = (char const   * __restrict  )" %i";
    printf(__cil_tmp21, 0);
    }
  } else {

  }
  {
  tmp___0 = isFloorCalling(1);
  }
  if (tmp___0) {
    {
    __cil_tmp22 = (char const   * __restrict  )" %i";
    printf(__cil_tmp22, 1);
    }
  } else {

  }
  {
  tmp___1 = isFloorCalling(2);
  }
  if (tmp___1) {
    {
    __cil_tmp23 = (char const   * __restrict  )" %i";
    printf(__cil_tmp23, 2);
    }
  } else {

  }
  {
  tmp___2 = isFloorCalling(3);
  }
  if (tmp___2) {
    {
    __cil_tmp24 = (char const   * __restrict  )" %i";
    printf(__cil_tmp24, 3);
    }
  } else {

  }
  {
  tmp___3 = isFloorCalling(4);
  }
  if (tmp___3) {
    {
    __cil_tmp25 = (char const   * __restrict  )" %i";
    printf(__cil_tmp25, 4);
    }
  } else {

  }
  {
  __cil_tmp26 = (char const   * __restrict  )"\n";
  printf(__cil_tmp26);
  }
  return;
}
}
void printState__role__overloaded(void) 
{ int tmp ;
  char const   * __restrict  __cil_tmp2 ;

  {
  {
  tmp = isBlocked();
  }
  if (tmp) {
    {
    __cil_tmp2 = (char const   * __restrict  )"Blocked ";
    printf(__cil_tmp2);
    }
  } else {

  }
  {
  printState__before__overloaded();
  }
  return;
}
}
void printState(void) 
{ 

  {
  if (__SELECTED_FEATURE_overloaded) {
    {
    printState__role__overloaded();
    }
    return;
  } else {
    {
    printState__before__overloaded();
    }
    return;
  }
}
}
*/


int existInLiftCallsInDirection(int d ) 
{ int retValue_acc ;
  int i ;
  int i___0 ;

  {
  if (d == 1) {
    i = 0;
    i = currentFloorID + 1;
    
    while (i < 5) {

      if ((i == 0) && (floorButtons_0==1)) {

          retValue_acc = 1;
          //return (retValue_acc);

      } else { 
        if ((i == 1) && (floorButtons_1==1)) {

            retValue_acc = 1;
            //return (retValue_acc);

        } else {

          if ((i == 2) && (floorButtons_2==1)) {
              retValue_acc = 1;
              //return (retValue_acc);

          } else {

            if ((i == 3) && (floorButtons_3==1)) {

                retValue_acc = 1;
                //return (retValue_acc);

            } else {
              if ((i == 4) && (floorButtons_4==1)) {

                  retValue_acc = 1;
                  //return (retValue_acc);

              } else {

              }
            }
          }
        }
      }
      i = i + 1;
    }

    
  } else {
    if (d == 0) {
      i___0 = 0;
      i___0 = currentFloorID - 1;
      {
      while (i___0 >= 0) {

        i___0 = currentFloorID + 1;
        {
        while (i___0 < 5) {

          if ((i___0 == 0) && (floorButtons_0==1)) {

              retValue_acc = 1;
              //return (retValue_acc);

          } else {

            if ((i___0 == 1) && (floorButtons_1==1)) {
                retValue_acc = 1;
                //return (retValue_acc);

            } else {
              if ((i___0 == 2) && (floorButtons_2==1)) {

                  retValue_acc = 1;
                  //return (retValue_acc);

              } else {

                if ((i___0 == 3) && (floorButtons_3==1)) {

                    retValue_acc = 1;
                    //return (retValue_acc);

                } else {

                  if ((i___0 == 4) && (floorButtons_4==1)) {

                      retValue_acc = 1;
                      //return (retValue_acc);
                  } else {

                  }
                }
              }
            }
          }
          i___0 = i___0 + 1;
        }

        }
        i___0 = i___0 - 1;
      }

      }
    } else {

    }
  }
  retValue_acc = 0;
  return (retValue_acc);
  //return (retValue_acc);
}
}

int isExecutiveFloorCalling(void) 
{ int retValue_acc ;

  
  
  retValue_acc = isFloorCalling(executiveFloor);
  
  return (retValue_acc);
  //return (retValue_acc);

}

int isExecutiveFloor(int floorID ) 
{ int retValue_acc ;

  
  retValue_acc = executiveFloor == floorID;
  return (retValue_acc);
  //return (retValue_acc);

}
